/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package taller.vistas;

import Imagenes.ImagendeFondo;
import java.io.IOException;
import java.security.Principal;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author martin
 */
public class VistaPrincipal extends javax.swing.JFrame {

     private ImagendeFondo es;
     
    public VistaPrincipal() {
         try {
          es= new ImagendeFondo();
          this.setContentPane(es);
          initComponents();
      } catch (IOException ex) {
          Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
      }
        
    }
 
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMgestionar = new javax.swing.JMenuItem();
        JMIgestion = new javax.swing.JMenuItem();
        JMGestion = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        JMIlistado = new javax.swing.JMenuItem();
        JMListaClientes = new javax.swing.JMenuItem();
        JMRepuesto = new javax.swing.JMenu();
        JMIGestion = new javax.swing.JMenuItem();
        JMReparacion = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("All Bike");

        jMenu2.setText("Gestionar");

        jMenuItem1.setText("Bicicletas");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem1);

        jMgestionar.setText("Servicios");
        jMgestionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMgestionarActionPerformed(evt);
            }
        });
        jMenu2.add(jMgestionar);

        JMIgestion.setText("Repuesto");
        JMIgestion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMIgestionActionPerformed(evt);
            }
        });
        jMenu2.add(JMIgestion);

        JMGestion.setText("Cliente");
        JMGestion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMGestionActionPerformed(evt);
            }
        });
        jMenu2.add(JMGestion);

        jMenuItem2.setText(" Reparaciones");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem2);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Listados");

        JMIlistado.setText("Listado de repuesto");
        JMIlistado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMIlistadoActionPerformed(evt);
            }
        });
        jMenu3.add(JMIlistado);

        JMListaClientes.setText("Listado de clientes");
        JMListaClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMListaClientesActionPerformed(evt);
            }
        });
        jMenu3.add(JMListaClientes);

        jMenuBar1.add(jMenu3);

        JMRepuesto.setText("Facturacion");

        JMIGestion.setText("Hacer Factura");
        JMIGestion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMIGestionActionPerformed(evt);
            }
        });
        JMRepuesto.add(JMIGestion);

        jMenuBar1.add(JMRepuesto);
        jMenuBar1.add(JMReparacion);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 774, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 553, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMgestionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMgestionarActionPerformed
       es.removeAll();
        es.repaint();
        VistaServicio vistaServicio = new VistaServicio();
        vistaServicio.setVisible(true);
        es.add(vistaServicio);
        es.moveToFront(vistaServicio);
    }//GEN-LAST:event_jMgestionarActionPerformed

    private void JMIgestionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMIgestionActionPerformed
        es.removeAll();
        es.repaint();
        VistaRepuesto gestionRepuesto = new VistaRepuesto();
        gestionRepuesto.setVisible(true);
        es.add(gestionRepuesto);
        es.moveToFront(gestionRepuesto);
    }//GEN-LAST:event_JMIgestionActionPerformed

    private void JMIlistadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMIlistadoActionPerformed
        es.removeAll();
        es.repaint();
        VistaListadoRepuesto listadoRepuesto = new VistaListadoRepuesto();
        listadoRepuesto.setVisible(true);
        es.add(listadoRepuesto);
        es.moveToFront(listadoRepuesto);
    }//GEN-LAST:event_JMIlistadoActionPerformed

    private void JMGestionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMGestionActionPerformed
        es.removeAll();
        es.repaint();
        VistaCliente clientesGestion = new VistaCliente();
        clientesGestion.setVisible(true);
        es.add(clientesGestion);
        es.moveToFront(clientesGestion);
    }//GEN-LAST:event_JMGestionActionPerformed

    private void JMIGestionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMIGestionActionPerformed
        es.removeAll();
        es.repaint();
        VistaReparacion clientesGestion = new VistaReparacion();
        clientesGestion.setVisible(true);
        es.add(clientesGestion);
        es.moveToFront(clientesGestion);
        // VistaReparacion reparacionGestion = new VistaReparacion(); (No funca);

    }//GEN-LAST:event_JMIGestionActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        es.removeAll();
        es.repaint();
        VistaBicicleta bicicletaGestion = new VistaBicicleta();
        bicicletaGestion.setVisible(true);
        es.add(bicicletaGestion);
        es.moveToFront(bicicletaGestion);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        es.removeAll();
        es.repaint();
        VistaGestionReparaciones GestionReparaciones = new VistaGestionReparaciones();
        GestionReparaciones.setVisible(true);
        es.add(GestionReparaciones);
        es.moveToFront(GestionReparaciones);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void JMListaClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMListaClientesActionPerformed
        es.removeAll();
        es.repaint();
        VistaListadoCliente listadoClientes = new VistaListadoCliente();
        listadoClientes.setVisible(true);
        es.add(listadoClientes);
        es.moveToFront(listadoClientes);
    }//GEN-LAST:event_JMListaClientesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem JMGestion;
    private javax.swing.JMenuItem JMIGestion;
    private javax.swing.JMenuItem JMIgestion;
    private javax.swing.JMenuItem JMIlistado;
    private javax.swing.JMenuItem JMListaClientes;
    private javax.swing.JMenu JMReparacion;
    private javax.swing.JMenu JMRepuesto;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMgestionar;
    // End of variables declaration//GEN-END:variables
}
